import com.squareup.kotlinpoet.*
import java.io.File
import java.text.SimpleDateFormat
import java.util.*
import java.util.Date

buildscript {
    repositories { mavenCentral() }

    dependencies { classpath("com.squareup:kotlinpoet:" + properties["kotlinPoetVersion"]) }
}

val currentDateAndTime = Date()
val formatter = SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
val formattedDateAndTime = formatter.format(currentDateAndTime)

/**
 * Goes through RestAPIMethods folder and generates a getter for every interface and puts it in the
 * interface RestAPIMethodGetters. Generate all this in the build folder with the path
 * io/ydwk/yde/api/rest/methods
 */
fun generateRestAPIMethodGetters() {
    val fileContainingAllRestAPIMethods =
        File(projectDir, "src/main/kotlin/io/github/ydwk/yde/rest/methods")

    val interfaceNames = mutableListOf<String>()
    fileContainingAllRestAPIMethods.walk().forEach {
        if (it.isFile && it.name.endsWith(".kt")) {
            val interfaceName = it.name.substring(0, it.name.length - 3)
            interfaceNames.add(interfaceName)
        }
    }

    val restAPIMethodGettersInterface =
        FileSpec.builder("io.github.ydwk.yde.rest.methods", "RestAPIMethodGetters")
            .addType(
                TypeSpec.interfaceBuilder("RestAPIMethodGetters")
                    .addModifiers(KModifier.PUBLIC)
                    .addAnnotation(
                        AnnotationSpec.builder(Suppress::class).addMember("\"UNUSED\"").build())
                    .addAnnotation(
                        AnnotationSpec.builder(
                                ClassName("javax.annotation.processing", "Generated"))
                            .addMember("\"Generated by YDE\"")
                            .addMember("date = " + "\"$formattedDateAndTime\"")
                            .build())
                    .addFunctions(
                        interfaceNames.map {
                            FunSpec.builder("get${it}")
                                .addModifiers(KModifier.ABSTRACT)
                                .returns(ClassName("io.github.ydwk.yde.rest.methods", it))
                                .build()
                        })
                    .build())
            .build()

    File("${project.layout.buildDirectory.get().getAsFile()}/generated/kotlin").apply {
        mkdirs()
        restAPIMethodGettersInterface.writeTo(this)
    }
}

task("generateRestAPIMethodGetters") {
    group = "generate"
    generateRestAPIMethodGetters()
}
